# Generated by Django 5.0.2 on 2024-02-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
